export const STREAM = {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  CREATE: "CREATE_STREAM",
  FETCHALL: "FETCH_STREAMS",
  FETCH: "FETCH_STREAM",
  DELETE: "DELETE_STREAM",
  EDIT: "EDIT_STREAM",
};
